### ISSUE TITLE
What exactly does the hl themes do?

### ISSUE THREAD

**Issue by Collatz124** [NvChad/nvim-base16.lua#31]
This is not really an issue, however I seem to have miss understood something when I created the Monekai theme. What exactly is the role of the hl part of a theme (I thought that it exclusively influenced the way that the UI looked, ie. not syntax highlighting), however i can not seem to figure out why the base feilds in the dictionary is colored aswell as the commas?

![Screenshot from 2021-12-12 22-04-51](https://user-images.githubusercontent.com/60628290/145729551-719af46e-bdb1-4d09-be84-8774f8b679eb.png)
 
Sorry for the extra work, appriciate it :sweat_smile: 

Sincerely Martin

**Comment by siduck** [comment]
the hl_themes are used for highlighting statusline  ,bufferline etc . check lua/colors/highlights.lua  , lua/plugins/bufferline , lua/plugins/statusline. 3 of these files use colors from the hl_themes

**Comment by Collatz124** [comment]
I found the mistake in the configuration of the Monekai theme, completely my bad :sweat_smile:, ill summit a pull request layer :)

Thank you.
