### ISSUE TITLE
feature to override a specific color for a theme

### ISSUE THREAD

**Issue by rambhosale** [NvChad/nvim-base16.lua#48]
For a particular theme like onebright I like the overall theme but I want to override a specific color like something similar to the following
eg 
```
theme.override("base00", "282c34")
theme.override("black", "282c34")
```
Currently, there is no direct feature or a way to achieve it from what I know
would really love to have this option

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config#override-specific-colors-in-themes
