### ISSUE TITLE
Not all themes converted to 0.7

### ISSUE THREAD

**Issue by i3Cheese** [NvChad/nvim-base16.lua#56]
Please, convert the following themes 
[kanagawa-base16.lua](https://github.com/NvChad/nvim-base16.lua/blob/master/lua/themes/kanagawa-base16.lua)
[onebright-base16.lua](https://github.com/NvChad/nvim-base16.lua/blob/master/lua/themes/onebright-base16.lua)
[wombat-base16.lua](https://github.com/NvChad/nvim-base16.lua/blob/master/lua/themes/wombat-base16.lua)

**Comment by siduck** [comment]
@i3Cheese add a PR!

**Comment by max397574** [comment]
@siduck can be closed ig
